version: 2
updates:
  - package-ecosystem: mix
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: cargo
    directory: "/native/pactmockserver"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
