language: elixir
elixir: '1.9'
otp_release: '22.0'

cache:
  directories:
  - $HOME/otp/

# https://askubuntu.com/questions/408784/after-doing-a-sudo-apt-get-install-app-where-does-the-application-get-stored
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y --no-install-recommends rustc cargo
  - rustc --version
  - cargo --version
  # - dpkg -L rustc
  # - dpkg -L cargo
  # - dpkg -L libhttp-parser2.1
  # - dpkg -L libssh2-1
  # - dpkg -L libstd-rust-1.24
  # - dpkg -L libstd-rust-dev

env: MIX_ENV=test

# Compiling PactMockServer outputs a warning {:error, {:upgrade, 'Upgrade not supported by this NIF library.'}} which
# swallows coverage results for it. Running test twice solves this for now.
script:
  - mix test
  - mix coveralls.travis

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
